services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_CONFIG=/var/lib/ollama/config.yaml
    deploy:
      resources:
          limits:
              cpus: 8.00
              memory: 10G
          # reservations:
          #     cpus: 1.00
          #     memory: 128M
          # reservations:
          #     devices:
          #       - driver: nvidia
          #         count: 1
          #         capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: ollama_webui
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_API_URL=http://ollama:8000
    depends_on:
      - ollama

volumes:
  ollama_data:
  open-webui: